const orderExample = {
    address: {
        id: 123,
        company_name: null,
        name: "John Doe",
        city: "Sample City",
    },
    client_details: {
        building_number: "-",
        city: "Sample City",
        company_name: null,
        floor: "-",
        house_number: "-",
        id: 123,
        name: "John Doe",
        nip: "-",
        phone: "123456789",
        postcode: "00000",
        street: "Sample Street 1",
        surname: "-",
    },
    comment: null,
    created_at: "2023-01-01T00:00:00.000000Z",
    delivery_cost: "-",
    delivery_time: "-",
    delivery_type: "-",
    discount: "-",
    dishes: [
        {
            additions: [],
            name: "Sample Dish",
            price: "4,20 PLN",
            quantity: 1,
        },
    ],
    games_payment: "-",
    id: 101,
    orders: [
        {
            id: 10,
            dish_id: 82,
            table_id: null,
            quantity: 1,
            price: "57.90",
            status: 1,
            paid: 0,
            tax: null,
            discount: "0.00",
            bill_id: 10,
            user_id: 1417,
            accepted_at: null,
            released_at: null,
            additions_price: "0.00",
            package_price: null,
            dish: {
                id: 82,
                name: "Zagraniczna",
                description:
                    "cienkie ciasto, sos, ser mozzarella, kurczak w ziołach, pomidory suszone, ser pleśniowy, oregano",
                price: "57.90",
                visibility: 1,
                tax: null,
                discount: "0.00",
                time_wait: 30,
                delivery: 1,
                position: 0,
                deleted_at: null,
                name_translation: {
                    de: null,
                    en: null,
                    pl: "Zagraniczna",
                },
                description_translation: {
                    de: null,
                    en: null,
                    pl: "cienkie ciasto, sos, ser mozzarella, kurczak w ziołach, pomidory suszone, ser pleśniowy, oregano",
                },
            },
        },
    ],
    paid: 1,
    paid_type: "cash",
    payment_at: "2023-01-02 12:00:00",
    payment_type: "-",
    personal_pickup: null,
    phone: "123456789",
    points: 500,
    points_refunded: 0,
    points_value: "-",
    room_delivery: null,
    service_charge: "-",
    status: 1,
    table_number: "-",
    ticket: 1,
    time_wait: "-",
    tip: "-",
    user: null,
    user_id: 456,
    user_res_id: null,
};

export default orderExample;
