<?php

namespace App\Http\Livewire\Datatables;

use App\Models\DeliveryRange;
use Rappasoft\LaravelLivewireTables\Views\Column;

class DeliveryRangeDatatable extends BaseDatatable
{
    protected $model = DeliveryRange::class;

    public function configure(): void
    {
        $this->createLink = route('admin.delivery_ranges.create');
        parent::configure(); // TODO: Change the autogenerated st
    }

    public function columns(): array
    {
        return [
            Column::make('ID', 'id')
                ->sortable(),
            Column::make(__('admin.Name'), 'name')
                ->format(
                    function ($value, DeliveryRange $row, Column $column) {
                        return $row->name ?? '-';
                    }
                )
                ->sortable()
                ->searchable(),
            Column::make(__('admin.Min order value'), 'min_value')
                ->format(
                    function ($value, DeliveryRange $row, Column $column) {
                        return $row->min_value ?? '-';
                    }
                )
                ->sortable(),
            Column::make(__('admin.Free delivery from'), 'free_from')
                ->format(
                    function ($value, DeliveryRange $row, Column $column) {
                        return $row->free_from ?? '-';
                    }
                )
                ->sortable(),
            Column::make(__('admin.Cost of delivery'), 'cost')
                ->sortable(),
            Column::make(__('admin.Actions'), 'id')
                ->format(
                    function ($value, DeliveryRange $row, Column $column) {
                        return view('components.admin.datatable.actions', [
                            'buttons' => [
                                $this->prepareDeleteButton($row->id, 'delivery_range', 'delivery_ranges'),
                            ],
                        ]);
                    }
                )
                ->html(),
        ];
    }
}
